import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  Brain, 
  Target, 
  BookOpen, 
  BarChart, 
  Zap, 
  Users,
  Clock,
  Award,
  MessageCircle
} from "lucide-react";

const Features = () => {
  const features = [
    {
      icon: Brain,
      title: "AI Study Plans",
      description: "Personalized learning paths generated by AI based on your goals and learning style.",
      color: "accent"
    },
    {
      icon: Target,
      title: "Smart Quizzes",
      description: "Intelligent quiz generation that adapts to your knowledge gaps and reinforces weak areas.",
      color: "primary"
    },
    {
      icon: BarChart,
      title: "Progress Analytics",
      description: "Detailed insights into your learning progress with visual charts and performance metrics.",
      color: "secondary"
    },
    {
      icon: BookOpen,
      title: "Note Organization",
      description: "Smart categorization and searchable notes with AI-powered content suggestions.",
      color: "warning"
    },
    {
      icon: Zap,
      title: "Instant Feedback",
      description: "Real-time feedback on your performance with actionable improvement suggestions.",
      color: "accent"
    },
    {
      icon: Clock,
      title: "Time Management",
      description: "AI-optimized study schedules that fit your lifestyle and maximize productivity.",
      color: "primary"
    }
  ];

  return (
    <section id="features" className="py-24 bg-background">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary-light rounded-full mb-6">
            <Zap className="w-4 h-4 text-primary" />
            <span className="text-sm font-medium text-primary">Powerful Features</span>
          </div>
          
          <h2 className="text-3xl md:text-5xl font-bold text-foreground mb-4">
            Everything You Need to
            <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent"> Excel </span>
          </h2>
          
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Our AI-powered platform combines cutting-edge technology with proven learning methodologies 
            to help you achieve your academic goals faster than ever before.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card key={index} className="group hover:shadow-card transition-smooth border-0 shadow-card bg-gradient-to-b from-background to-muted">
                <CardHeader>
                  <div className={`w-12 h-12 rounded-lg ${
                    feature.color === 'accent' ? 'bg-gradient-to-r from-accent to-accent' :
                    feature.color === 'primary' ? 'bg-gradient-to-r from-primary to-primary' :
                    feature.color === 'secondary' ? 'bg-gradient-to-r from-secondary to-secondary' :
                    'bg-gradient-to-r from-warning to-warning'
                  } flex items-center justify-center mb-4 group-hover:shadow-glow transition-smooth`}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <CardTitle className="text-xl font-semibold text-foreground">
                    {feature.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-muted-foreground leading-relaxed">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Call to Action */}
        <div className="text-center">
          <Card className="max-w-4xl mx-auto bg-gradient-to-r from-primary to-accent border-0 shadow-elegant">
            <CardContent className="p-8">
              <div className="flex flex-col md:flex-row items-center gap-6">
                <div className="flex-1 text-left">
                  <h3 className="text-2xl font-bold text-primary-foreground mb-2">
                    Ready to Transform Your Learning?
                  </h3>
                  <p className="text-primary-foreground/90">
                    Join thousands of students who've improved their grades with StudyAI
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <Button variant="secondary" size="lg">
                    <Users className="w-5 h-5" />
                    Join Community
                  </Button>
                  <Button variant="outline" size="lg" className="bg-white/10 border-white/20 text-white hover:bg-white hover:text-primary">
                    <MessageCircle className="w-5 h-5" />
                    Contact Us
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
};

export default Features;