// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugwrdyjbmmaqvlnootag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnd3JkeWpibW1hcXZsbm9vdGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzY2OTAsImV4cCI6MjA3MTk1MjY5MH0.rQMpG9K0E9D_0w7MzMZ1DU78kp0hiRU1jZwASzLSMac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});